<?php 
// dynamic page title
$page_title="Terms of Use - V2";

// include the header 
include_once('sections/layouts/header.php') 
?>

<!-- .breadcrumb-section starts  -->
<div class="breadcrumb-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12 breadcrumb-area">
                <ol class="breadcrumb dark">
                    <li><a href="home.php"><i class="fa-solid fa-house"></i></a></li>
                    <li><a href="#">Help Center</a></li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- .breadcrumb-section ends  -->

<!-- .page-content starts  -->
<div class="section clearfix page-content">
    <div class="container">
        <!-- .page tittle  -->
        <div class="row">
            <header class="col-md-12 text-dark-color section-title small mb-4">
                <h1>Help Center</h1>
            </header>
        </div>
         <!-- .page tittle ends  -->
         
         
        <div class="row">
            <!-- sidebar starts  -->
            <aside class="col-md-3 page-sidebar">
                <div class="card">
                    <div class="card-body shadow">
                        <ul class="page-list">
                            <li class="active"><a href="terms-of-use.php">Terms of Use</a></li>
                            <li><a href="privacy-policy.php">Privacy Policy</a></li>
                            <li><a href="warranty.php">Warranty</a></li>
                            <li><a href="#">Cancellations/Returns</a></li>
                            <li><a href="#">Shipping & Delivery</a></li>
                            <li><a href="#">Gazebos & Playsets</a></li>
                        </ul>
                    </div>
                </div>
            </aside>
            <!-- sidebar ends  -->
            
            <!-- .main-content  -->
            <section class="col-md-9 main-content mb-5">
                <div class="article-title">
                    <h3>Terms of Use</h3>
                </div>
                <article class="sub-article">
                    <h4>Last Updated: February 2023</h4>
                    <p>Welcome to <i>www.cabinfield.com</i>, an ecommerce website for the purchase of classic Amish crafted furniture and other products (the "<u>Website</u>").  We are happy you have chosen to visit us!   The Website is operated by Cabinfield Woodworking LLC, a New Jersey limited liability company with an address at 15 Cabinfield Circle, Lakewood, NJ 08701 (“<u>Cabinfield</u>”, “<u>we</u>”, “<u>our</u>”, or “<u>us</u>”). Anonymous visitors to the Website ("<u>Visitors</u>") can browse our content.  Visitors who are at least eighteen (18) years of age and not a minor in their state or residence, and who affirmatively indicate their agreement to abide by these Terms of Use (this “<u>Agreement</u>”) by means of a click-through consent (if and where this option is made available by Cabinfield) (“<u>Registrants</u>”) can purchase any of products and/or services offered through the Website or otherwise by us (collectively, “<u>Products</u>”) and can use additional Website functionality. The terms “<u>you</u>”, "<u>your</u>" and “<u>yours</u>” when used in this Agreement refer to either Registrants or Visitors, or to both Registrants and Visitors together, as applicable; provided that such terms will refer to both Registrants and Visitors together unless the context of this Agreement indicates otherwise. This Agreement sets forth the terms and conditions which govern your use of the Website.</p>
                </article>
                <article class="point-section">
                    <h4 class="heading">This Agreement</h4>
                    <h5 class="point">Acceptance</h5>
                    <p>Please read this Agreement carefully before otherwise accessing the Website. In order to use the Website, you must first agree to be bound by the provisions of this Agreement. You indicate that you have read, understood and agreed to be bound by the provisions of this Agreement by means of a click-through consent (where provided by us) or otherwise by accessing the Website, or as further described below by confirming one of our Product orders by electronic mail. If you do not agree to be bound by this Agreement, you are not authorized to use the Website or otherwise to purchase any Products.  You also are not authorized to use the Website if (a) you are not of legal age or otherwise do not have the legal capacity to form a binding contract with Cabinfield, or (b) you are a person barred from using the Website either (i) under the laws of the country in which you reside or from which you are attempting to access the Website, or (ii) due to prior violations of this Agreement.</p>
                    <h5 class="point">Modification</h5>
                    <p>We reserve the right to modify this Agreement at any time. You shall periodically review this Agreement to be aware of such modifications. You further agree that your continued use of the Website after any such modifications have been made shall be deemed to be your conclusive acceptance of any modified version of this Agreement. We will indicate that changes to this Agreement have been made by updating the date indicated after “Last Updated” at the beginning of this Agreement, and any updated supplemental policy or other terms (which are a material part of this Agreement as indicated below) will be indicated in the same manner. We will be happy to provide you with prior versions of this Agreement (including any supplemental policy or other terms) upon your written request to us. If you do not agree to abide by the initial version and each modified version of this Agreement, then you are not authorized to use the Website. A current version of this Agreement is accessible via the footer of the Website’s homepage.</p>
                </article>
                
                <article class="point-section">
                    <h4 class="heading">Registration</h4>
                    <h5 class="point">Account</h5>
                    <p>A Registrant who registers with us will receive a unique account (“<u>Account</u>”) and will be able to access such Account by selecting a corresponding user ID and password. You shall not allow any individual or entity to use your Account to access the Website or otherwise to contact us and you shall strictly safeguard your user ID and password and any other information that would allow any person to access the Website or otherwise to contact us by using your Account. You are solely responsible for your failure to strictly safeguard such information and/or to allow any other person to access or use the Website or otherwise to contact us by using your Account.  You may not sell or otherwise transfer your Account or any portion thereof. You shall notify Cabinfield immediately of any unauthorized use of your Account or any portion of the Website. Cabinfield shall not be liable for any loss that results from the unauthorized use of your Account, either with or without your knowledge. </p>
                    <h5 class="point">Accurate Information</h5>
                    <p>You shall provide accurate, complete and current information about yourself when registering for your Account and otherwise when using the Website, and you shall update all information provided by you through the Website if and as soon as such information changes.</p>
                    <h5 class="point">Disabling or Revoking of Account</h5>
                    <p>We have the right to suspend or terminate your Account at any time if we believe you have violated or are likely to violate this Agreement, all as determined by us in our sole discretion.  If we suspend, terminate or otherwise disable access to your Account, you may be prevented from accessing certain portions of the Website, including your Account details and/or any the comments, icons, images, messages, tags, links, photographs, audio, video and other like content appearing on the Website (collectively, “<u>Content</u>") which was uploaded or otherwise provided through your Account or otherwise by you to the Website or otherwise to us (collectively, “<u>Your Content</u>”), all of which may be deleted by us.  In such a case, your rights to use the Website and any Your Content may cease immediately. Suspension or termination by us is without prejudice to all other remedies available to Cabinfield by law or under this Agreement.</p>
                    <h5 class="point">Cessation of Functionality; Change of Products</h5>
                    <p>As part of our continuing innovation, we may stop (permanently or temporarily) providing certain Website features to you in our sole discretion, without prior notice to you. The form and nature of the any of the Products may change from time to time without prior notice to you.</p>
                </article>
                <article class="point-section">
                    <h4 class="heading">Transactions</h4>
                    <h5 class="point">Purchases</h5>
                    <p>All of the Products are acquired by you on a “AS IS” and “WHERE IS” basis. If you wish to purchase any of the Products, you shall comply with the applicable provisions of this Agreement as well as the provisions of any ancillary policies, terms, conditions or agreements which govern your purchase of any of the Products. To the extent we have the authority to do so, we reserve the right (but do not have the obligation) to correct any errors or mistakes made by our ecommerce service provider even if it has already requested or received payment from you, though we are not responsible for errors by our ecommerce gateway or other service providers and any recourse you wish to seek which relates to any such error shall be directly to such service provider. Thus, we may cancel any order that was based on erroneous information (e.g., an incorrect price). Further, we may refuse to sell to you for any reason (as determined by us in our sole discretion) given your past history or otherwise. You will use all Products you purchase for their intended use only.</p>
                   
                    <h5 class="point">Orders</h5>
                    <p>You may purchase the Products through the Website or through a phone order with our trained staff.  We offer you many different Product options (e.g., model, size, color, finish) which you can select in ordering the Products through the Website (each, a “<u>Standard Order</u>” and collectively, “<u>Standard Orders</u>”).  Alternatively, you may create a custom order of the Products (or your own conceived product that we agree to produce) by selecting options beyond those offered through the Website (each, a “<u>Custom Order</u>” and collectively, “<u>Custom Orders</u>”) by means of a  phone order. The parameters and specifications of all Standard Orders will be confirmed on a confirmation page through the Website prior to the execution of your Standard Order. Thus, by executing a Standard Order with us, you affirm that you have selected each specific Product so identified immediately prior to executing your order.  All Custom Orders will be made by means of a phone order with us which will be memorialized in a follow-up email confirmation (the “<u>Confirmation</u>”).  Your affirmative approval of the Confirmation (by email or facsimile) will be required in order for us to start processing your order. All orders submitted through the Website, or over the phone and confirmed by you, are FINAL.  Note that all orders placed supersede any prior phone, email or other communications with us, and the options and specifications provided at the time your order is placed are FINAL.  So please be very careful to inspect the details of each order before you confirm, because you understand that your Product will be built exclusively according to the provisions of the applicable Confirmation for such order.  The only exception to the above policy is any revised order form that may be later approved (and signed in writing) by us; otherwise you are bound to accept the options and specifications of each Product purchased by you and as confirmed by you in  your Confirmation.  If you do not receive a Confirmation from us right after placing a Custom Order, please check your email “Junk” folder to make sure the Confirmation has not been routed there. In the even you do not receive any Confirmation shortly after placing your order, you agree to contact us immediately in order to notify us of such an issue. </p>
                    
                    <h5 class="point">Payments</h5>
                    <p>Your submission of a check to us, or your request for us to charge your credit card by providing your credit card information to us or to our ecommerce gateway or other service provider, indicates your express authorization for us (or such third party) to charge your credit card for the associated purchase requested by you. By making a purchase through the Website, you agree to pay us (or our ecommerce gateway or other service provider, as the case may be) all charges at the prices then in effect using the payment method selected by you. Your right to receive any of the Products is conditional on our prior receipt of the full payment and related costs for each such Product. If all such payment and costs cannot be charged to your credit card or if a charge is refunded for any reason, including by chargeback, we reserve the right to refuse to deliver the Product you ordered and/or cancel your order, as determined by us in our sole discretion. Again, you are fully responsible for all charges made under your Account or otherwise in your name, and you will pay us all fees associated with any returned check or other reversal of any purchase by you. Your credit card payment may be rejected if we (or a third party working on our behalf) detect the presence of certain fraud indicators. Whether a credit card is accepted or rejected is not always determined by information provided by the cardholder, and we apologize for any inconvenience for orders where a credit card payment is not possible. For international orders, Cabinfield may, at its sole discretion, require payment by wire transfer, and all such purchases shall be in US Dollars. Please note that there are certain non-refundable deposits which apply to our orders, and this issue is described in detail in our Cancellation and Return Policy referenced in Section 3.8 below.</p>
                   
                    <h5 class="point">Our Warranty</h5>
                    <p>Our Warranty Policy can be found at <a href="/page/our-warranty.html">http://dev-new.cabinfield.com/page/our-warranty.html</a> and is an integral part of, and is incorporated into, this Agreement. </p>
                   
                    <h5 class="point">Descriptions</h5>
                    <p>We attempt to be fully accurate in describing the Products (including, without limitation, the price of each Product) offered for purchase by us through the Website; however, we do not warrant or represent that all such descriptions are complete, current or error-free. Further, all such descriptions are subject to change at any time (even after a purchase has been effectuated) and without notice, in our sole discretion. We are not responsible for any such errors and we have the right (as exercised by us in our sole discretion) to change or cancel any orders which were made based on any missing or inaccurate information. For clarity, if your order was based on any inaccurate description, we may (as determined by us in our sole discretion) either notify you of any necessary price adjustments prior to final processing and shipment of the order or we may cancel your order and refund you any payments already made by you for such order.</p>
                   
                    <h5 class="point">Color</h5>
                    <p>Further to the above in Section 3.5 but specifically with regard to the staining of wood, you acknowledge and understand that wood is an organic material and colors stain in different ways (even the same color with the same type of wood has variations) given the different grades of natural wood and other variables involved in creating each Product. Thus, we cannot guarantee any uniform color palate for any of the Products, and the colors we offer usually fall within a certain range or tones. If you are especially concerned about a particular color for a Product you wish to order, then we suggest you request us to send you a stain sample or samples to help you decide on the stain that will work best for you. For an additional fee, we undertake additional efforts to match the sample sent to you (we call this additional service a “stain match”), and often these efforts do result in a closer color match. But please note that even if we have undertaken a “stain match” for the Product ordered by you, we cannot guarantee a precise shade of stain for that Product. While our samples are excellent approximations, they may vary from the actual stain on the Product you receive (again, these variations occur naturally as a result of differences in wood grain, type of wood, stain composition, and other naturally occurring factors). Thus, we cannot be and are not responsible for any differences between the sample color and the final color of the stain you choose for your ordered Product. We provide these stain samples free of charge, provided that you ship them back to us at your cost.</p>
                    
                    <h5 class="point">Shipping and Delivery</h5>
                    <p>Our Shipping and Deliver Policy can be found at <a href="/page/shipping.html">http://dev-new.cabinfield.com/page/shipping.html</a> and is an integral part of, and is incorporated into, this Agreement.</p>
                    
                    <h5 class="point">Cancellation and Return Policy</h5>
                    <p>Our Cancellation and Return Policy can be found at <a href="/page/cancellation.html">http://dev-new.cabinfield.com/page/cancellation.html</a> and is an integral part of, and is incorporated into, this Agreement.</p>
                    
                    <h5 class="point">Reservation of Rights; Modifications</h5>
                    <p>The raw materials of some of the Products may have limited quantities and we cannot guarantee the availability of any Product. We also cannot guarantee that any Product will meet your expectations. We reserve the right, but are not obligated, to limit or discontinue the sale of any of the Products to any person (including without limitation the quantity of any specific of the Products), geographic region or jurisdiction, or otherwise, and we may exercise this right on a case-by-case basis in our sole discretion. The offer of any of the Products made through the Website or otherwise is void where prohibited. We further reserve the right to limit or prohibit orders of any of the Products that, in our sole judgment, appear to be placed by persons who are dealers, resellers or distributors, whether or not they have so identified themselves to us.</p>
                    
                    <h5 class="point">Taxes</h5>
                    <p>You are responsible for paying all applicable taxes arising out of any purchase of any of the Products made by you through the Website or otherwise, including without limitation all duties, taxes, and/or other fees that may apply to the import of any Products.</p>
                    
                    <h5 class="point">Your Personal Information</h5>
                    <p>In the event you wish to purchase any of the Products or use other certain functionality of the Website, you will be asked by Cabinfield and/or a third party working on our behalf to supply certain of your personally identifiable information (“<u>PII</u>”). You shall provide us and/or such third party (as applicable) with accurate, complete and current PII (including without limitation your email address and credit card number and expiration date), and you shall update all PII if and as soon as such information changes before you make any additional purchase of any the Products. You shall be responsible for all activity conducted through the Website which is identified with such information.</p>
                </article>
                <article class="point-section">
                    <h4 class="heading">Your Content: Usage Restrictions</h4>
                    <h5 class="point">Your Content</h5>
                    <p>You shall adhere to following terms and conditions for using the Website: (a) Cabinfield has no obligation to use or respond to any of Your Content, (b) the provision of Your Content to us in no way imposes any obligation on Cabinfield, whether of confidentiality, attribution, compensation or otherwise, and Cabinfield shall not be liable for any disclosure or other use of any of Your Content, (c) all Your Content shall be accurate and shall not violate the copyright, trademark, patent, trade secret, right of publicity, right to privacy, or any other intellectual property or other legal right of any third party, (d) you shall pay for all royalties, fees and any other monies owing any person by reason of any of Your Content that you post to the Website, (e) Your Content may be subject to size and usage limitations, and you are responsible for adhering to any such limitations, and (f) all of Your Content shall comply with the provisions of Section 4.3 below specifically as well as all other applicable sections of this Agreement.</p>
                    
                    <h5 class="point">Quality and Review of Your Content</h5>
                    <p>We do not and shall not have any obligation to review Your Content, and therefore we do not guarantee the accuracy, integrity or quality of any of Your Content or the Content of any other person, and thus we cannot assure that harmful, inaccurate, deceptive, offensive, threatening, defamatory, unlawful or otherwise objectionable Content will not appear on the Website. Notwithstanding the foregoing or anything to the contrary in this Agreement, Cabinfield (a) has the absolute right (but not the obligation) to pre-screen, monitor, review, flag, filter and remove any and all of Your Content in our sole discretion, and we reserve the right to alter, edit, refuse to post or remove any of Your Content, in whole or in part, for any reason or for no reason as determined by us in our sole discretion, and (b) has the right to disclose Your Content and the circumstances surrounding its transmission to any third party in order to satisfy any applicable law, regulation, legal process or governmental request or to protect ourselves, other Website users or service providers or any other person, as determined by us in our sole discretion.</p>
                    
                    <h5 class="point">Usage Restrictions</h5>
                    
                    <p>You shall not use the Website in any manner that:</p>
                    <p>(a) enables you (or enables any other person) to (i) copy, modify, create a derivative work of, any Content, or (ii) copy, modify, create a derivative work of, reverse engineer, translate, adapt or decompile (or attempt to translate, adapt or decompile) or otherwise attempt to extract any software underlying any portion of the Website or the source code of the software underlying the Website or any portion thereof;  </p>
                    <p>(b)  interferes with operations or services provided by the Website or otherwise disrupts the Website in any way; </p>
                    <p>(c) interrupts, destroys or limit the functionality of, any computer software or hardware or telecommunications equipment (including without limitation by means of software viruses, Trojan horses or any other computer code, files or programs);</p>
                    <p>(d) infringes any copyright, trademark, trade secret, patent or other right of any party (including the promoting of an illegal or unauthorized copy of another person's copyrighted work), or defames or invades the publicity rights or the privacy of any person, living or deceased (or impersonates any such person);</p>
                    <p>(e) is false, misleading, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, hateful, or racially, ethnically or otherwise objectionable, as determined by us in our sole discretion; </p>
                    <p>(f) creates a false identity or otherwise attempts to mislead any person as to the identity or origin of any communication; </p>
                    <p>(g) exports, re-exports, or permits downloading of any message or content in violation of any export or import law, regulation, or restriction of the United States and its agencies and authorities, or without all required approvals, licenses, or exemptions; </p>
                    <p>(h) causes us to lose (in whole or part) the services of our internet service providers or other suppliers;</p>
                    <p>(i) consists of any unsolicited or unauthorized advertising, promotional materials, “junk mail,” “spam,” “chain letters,” “pyramid schemes,” or any other form of solicitation;</p>
                    <p>(j) links to materials or other content, directly or indirectly, to which you do not have a right to link or which we determine in our sole discretion is not appropriate to be linked to from the Website; or</p>
                    <p>(k) violates, or encourages others to violate this Agreement (or engages in any other activity deemed by us to be in conflict with this Agreement), or violates or encourages others to violate any applicable local, state, national, or international law. </p>
                                    
                    
                    <h5 class="point">Reporting Violations</h5>
                    <p>You shall immediately notify us in writing of any of Your Content or of any other Content that you view through the Website which you deem to be offensive, inappropriate or otherwise a violation of this Agreement.</p>
                    
                    <h5 class="point">Disabling or Revocation of Use</h5>
                    <p>We have the right to cancel or suspend your use of the Website (if applicable) including without limitation any purchase made by you, for any reason (without having to specify the reason) or for no reason at any time, as determined in our sole discretion, including without limitation if we believe you have violated this Agreement.</p>
                </article>
                <article class="point-section">
                    <h4 class="heading">Intellectual Property</h4>
                    <h5 class="point">Proprietary Rights</h5>
                    <p>Content provided by Cabinfield or any of our third party licensors is protected by copyright, trademark and other laws of the United States and/or other jurisdictions.  Other than for Your Content and third party Trademarks (as defined below in Section 5.4) appearing on the Website, you acknowledge and agree that as between you and us, all right, title and interest (including without limitation all copyright, trademark, patent, trade secret and other intellectual property rights) in and to Website (including without limitation all other Content appearing therein) is owned by us, and that you have no rights in and to the Website other than as expressly set forth in this Agreement.  Except for that information which is in the public domain and is not otherwise limited by third party rights or for which you have been given express written permission by us, no Content (other than for Your Content as uploaded by you to the Website alone) may be sold, copied, reproduced, republished, uploaded, displayed, posted, transmitted, distributed, modified, publicly performed, used in any derivative works based thereon or otherwise used for any public or commercial purpose without our prior written consent or, where applicable, that of our licensors. However, you may print copies of materials on the Website for your personal, noncommercial use only, provided that you must keep intact all copyright, Trademark, and other proprietary notices appearing therein and that you use such materials only in the manner permitted by this Agreement and never in any manner which directly or indirectly competes with us.  For clarity and without limiting the foregoing, please note that Content posted by other Website users may also be protected by copyright, trademark patent and other rights under the laws of the United States and/or other jurisdictions, and no rights in such Content whatsoever are granted to you other than those expressly granted herein or by the owner of such Content.</p>
                    
                    <h5 class="point">Grant of License to your content</h5>
                    <p>By posting Your Content to the Website, you automatically grant, and represent and warrant that you have the right to grant to Cabinfield, a non-exclusive, perpetual, irrevocable, sub-licensable (through multiple tiers), assignable, fully-paid, royalty-free, and worldwide license to use, copy, modify, adapt, publish, make, sell, publicly display, create derivative works of or incorporate into other works all of such Your Content (in whole or in part), communicate to the public, distribute (through multiple tiers), perform or display all of such Your Content (in whole or in part), in any form, media, or technology now known or later developed, and to grant and authorize sublicenses of the foregoing through multiple tiers of sub-licensees, including the right to exercise the copyright, publicity, and any other rights over any of the materials contained in all of such Your Content for any purpose, including without limitation for purposes of advertising and publicity on the Website and elsewhere, and/or otherwise to generate any revenue.  We shall not be limited in any way in the use, commercial or otherwise, of any of Your Content, and you hereby waive any moral rights (or “droit moral”) in, or approval rights to, Your Content.  For clarity and without limiting the foregoing, we reserve the express right to incorporate any of Your Content into any further work, in any medium now or hereafter known, without prior consent or review, and without attribution or payment of any royalty or fee whatsoever.</p>
                    
                    <h5 class="point">Copyright Agent</h5>
                    
                    <p>The Digital Millennium Copyright Act of 1998 (the "<u>DMCA</u>") provides recourse for copyright owners who believe that material appearing on the Internet infringes their rights under U.S. copyright law.  If you believe that your work has been copied and posted on the Website in a way that constitutes copyright infringement, please provide our copyright agent with the following information: (a) an electronic or physical signature of the copyright owner or of the person authorized to act on behalf of the owner of the copyright interest, (b) a description of the copyrighted work that you claim has been infringed, (c) a description of where the material that you claim is infringing is located on the Website, (d) your address, telephone number, and e-mail address, (e) a written statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law, and (f) a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf.  Any notification by a copyright owner or a person authorized to act on its behalf that fails to comply with requirements of the DMCA shall not be considered sufficient notice and shall not be deemed to confer upon us actual knowledge of facts or circumstances from which infringing material or acts are evident.  Our copyright agent for notice of claims of copyright infringement can be reached as follows:</p>
                    <address>
                        <p>Name: Cabinfield LLC Copyright Agent<br>
                            Address: 15 Cabinfield Circle, Lakewood, NJ 08701<br>
                            Telephone: 	866-450-9663<br>
                            Email: <a href="mailto:service@cabinfield.com">service@cabinfield.com</a></p>
                    </address>
                    <p>We suggest that you consult your legal advisor before filing a notice with our copyright agent.  You should note that there can be penalties for false claims under the DMCA.  We will, in appropriate circumstances and to the extent plausible, terminate the right of Website users who infringe the rights of copyright holders to interact with certain portions of the Website.</p>
                                    
                    
                    <h5 class="point">Trademarks</h5>
                    <p>“CABINFIELD” is a Trademark of Cabinfield.  All other Trademarks referenced on the Website are the property of their respective owners.  Cabinfield is not affiliated with or sponsored or endorsed by any trademark owner whose Trademark may appear on the Website and whose owner is not indicated to be Cabinfield. As used herein, the term “<u>Trademarks</u>” means, collectively, all service names, graphics, designs, logos, page headers, button icons, scripts, commercial markings, and trade dress appearing on the Website which indicate a source of goods or services. Trademarks are protected by the trademark laws of the United States and/or other jurisdictions. You may not use, copy, reproduce, republish, distribute or modify any Trademarks in any way, including without limitation in the distribution of any Content, for advertising or publicity or otherwise, without our prior written consent or the prior written consent of each such third party Trademark holder, as applicable.  Unless you have been expressly authorized to do so in writing by Cabinfield or any other applicable Trademark holder, you shall not use any Trademark in any way that is likely or intended to cause confusion with the owner of such Trademark.</p>
                    
                    <h5 class="point">Removal of Notices</h5>
                    <p>You shall not remove, obscure, or alter any proprietary rights or notices (including without limitation copyright and Trademark notices) which may be affixed to or contained within any Content. You shall abide by all such notices.</p>
                </article>
                
                <article class="point-section only-point">
                    <h4 class="heading">Links; Third Party Websites</h4>
                    <p>The Website may provide links to third party websites that we believe may be of potential interest to you. Because we do not endorse or otherwise have control over such websites, we are not responsible or liable, directly or indirectly, for (a) the availability of such websites, (b) any content, data, text, software, music, sound, photographs, video, messages, tags, links, advertising, services, products, or other materials on or available from such websites, (c) your participation, correspondence or business dealings with any third party regarding payment and delivery of specific goods and services, and any other terms, conditions, representations or warranties associated with such dealings, which are solely between you and any such third party, and (d) any damage or loss caused or alleged to be caused by or in connection with your interaction with any such third party or any other third party whom you form a connection with through or because of the Website. Your use of any website linked to from the Website is subject to the policies and procedures of the owner of such website and not to the terms and conditions of this Agreement.</p>
                </article>
                
                <article class="point-section only-point">
                    <h4 class="heading">Representations, Warranties and Covenants</h4>
                    <p>You represent and warrant that (a) you have all rights, power and the full legal authority to enter into this Agreement (and if you are entering into this Agreement on behalf of any entity that you are fully authorized by such entity to so enter into this Agreement on its behalf), (b) you have carefully read this Agreement and shall comply with all of your obligations under this Agreement, the Privacy Policy (as defined in Section 11 below) and any other terms or conditions posted on the Website, (c) this Agreement is enforceable against you in accordance with its terms and conditions, (d) you shall not disparage Cabinfield, any of our personnel, the Website or any of our Products, and (e) regarding Your Content, (i) you hereby waive any and all claims (including, without limitation, claims based upon invasion of privacy, defamation, false light, or right of publicity) arising out of or related to any alteration, distortion or other use of your name, image or likeness or that of any third party which appears in any of Your Content (including without limitation your photograph or the photograph of a third party), (ii) the posting of Your Content by you does not and shall not violate any terms and conditions to which you are bound under this Agreement, any other applicable agreement, or any applicable law or regulation, (iii) you will not use any of Your Content provided other than as expressly permitted in this Agreement, and (iv) you are solely responsible for (and Cabinfield has no responsibility to you or to any third party) any of Your Content that you create, transmit, display, submit or post while using the Website and for the consequences of your actions, including without limitation any loss or damage which Cabinfield of any of its affiliated entities or any of their shareholders, officers, directors, members, managers, licensors, agents, employees, consultants, representatives and service providers (collectively, the “<u>Cabinfield Parties</u>”) may suffer which is related to any of Your Content including without limitation the enforcement of any rights in and to any of Your Content.</p>
                </article>
                <article class="point-section only-point uppercase">
                    <h4 class="heading">DISCLAIMER OF WARRANTIES</h4>
                    <p>Your use of the website and any products you purchase from us are on an “as is” and “as available” basis, with all faults, and at your sole risk. Other than for any express written warranty provided by cabinfield in section 3.4 above, none of the cabinfield parties has or shall have any liability, obligation or responsibility to you or any other person for any loss, damage, or adverse consequence alleged to have happened or which has happened, directly or indirectly, through your use of the website or otherwise related to your purchase or your use of any products. Cabinfield further does not make any guaranty of the accuracy, correctness, usefulness or completeness of, and is not liable for any losses or damages alleged to arise from or arising from or related to, any use of the website or any use of any products. Specifically, and to the extent permitted by applicable law, cabinfield disclaims (a) all implied warranties of title, non-infringement, merchantability, and fitness for any particular purpose regarding the website and any products, and (b) all warranties not expressly made in this agreement, including without limitation in connection with your purchase of any products or otherwise your use of the website.  Cabinfield does not warrant that the website will be uninterrupted or error free or free from viruses or other harmful components. Further, under no circumstances shall cabinfield be liable in any way for any loss or damage alleged to arise or arising out of or related to your use of the website or any products, or your interaction with any third party linked to from the website or otherwise in connection with your purchase of any products.</p>
                </article>
                <article class="point-section only-point uppercase">
                    <h4 class="heading">Limitation of Liability</h4>
                    <p>In no event shall any of the cabinfield parties be liable for lost profits or for any special, incidental, indirect, consequential or punitive damages arising out of or related to, directly or indirectly, your use of (a) the website (including without limitation your use of any content appearing on the website or your loss of data, income, or profit, or loss or damage to property, arising out of or in connection with youe use of, or youe inability to use, the website), or (b) any products purchased from us or otherwise available through the website, whether or not any of the cabinfield parties has been advised of the possibility of such damages. The aggregate liability of the cabinfield parties collectively to you or any related person in all circumstances is limited to the lesser of (a) the cost of all products purchased by you from the website in the three (3) month period immediately prior to the arising of such liability, or (b) five hundred dollars ($500). Some jurisdictions do not allow for the exclusion of certain warranties or the limitation or exclusion of liability for special, incidental, indirect, consequential or punitive damages. Accordingly, some of the above limitations in section 8 above or this section 9 may not apply to you, but in such a case such liability will be limited to the greatest extent permitted by law.</p>
                </article>
                <article class="point-section only-point">
                    <h4 class="heading">Indemnification</h4>
                    <p>You shall indemnify, defend and hold harmless Cabinfield and each of the other Cabinfield Parties from all claims, demands, causes of action and/or lawsuits (each, a "<u>Claim</u>" and collectively, "<u>Claims</u>") and all resulting costs, liabilities, losses, expenses, and damages, actual and consequential, direct and indirect, of every kind and nature, including without limitation reasonable attorneys' fees and disbursements (collectively, "<u>Losses</u>") made by any third party arising out of or related to (a) the breach by you of any of your representations, warranties, covenants under this Agreement or your failure to fulfill any of your obligations under this Agreement, (b) your negligence or misconduct, or (c) your violation of any law or regulation.  You shall provide all applicable Cabinfield Parties with prompt written notice of any Claim or potential Claim of which you become aware.  Upon the assertion or commencement of any Claim against one or more of the Cabinfield Parties by any third party that may give rise to liability of any such Cabinfield Party hereunder, you shall assume the control of the defense of such Claim at your sole expense with counsel reasonably acceptable to each such applicable Cabinfield Party; provided, however, that each such Cabinfield Party may take part in and/or fully assume such defense, in its sole discretion and at its own expense, after you assume the control thereof.  You shall not enter into any settlement of any Claim which any of the Cabinfield Parties believes is adverse to its interests, without receiving the prior written consent of each of the Cabinfield Parties affected by such Claim.  In no event shall any of the Cabinfield Parties be obligated to participate in any settlement which any such party reasonably believes would have an adverse effect on such party’s business interests.</p>
                </article>
                <article class="point-section only-point">
                    <h4 class="heading">Privacy</h4>
                    <p>Cabinfield views the protection of your privacy as an important responsibility. The terms regulating the handling, use and storage of your PII and other information by us in connection with the Website is described in our Privacy Policy, which can be found at <a href="/page/privacy-security.html">http://dev-new.cabinfield.com/page/privacy-security.html</a> (the “<u>Privacy Policy</u>”). By using the Website, you consent to the collection and use of your PII by us as described in the Privacy Policy.  However, the handling, use and storage of your PII by any third party is subject to the privacy policy (if available) of such third party and not the Privacy Policy; for instance, when you provide your credit card information to our ecommerce gateway or other service providers, your PII will be subject to the privacy policy of our ecommerce gateway or other service providers.</p>
                </article>
                <article class="point-section only-point">
                    <h4 class="heading">No Endorsement</h4>
                    <p>Cabinfield is neither affiliated with, nor sponsored or endorsed by, any specific product, service, methodology or person. The owners of any third party product, service, information, Trademark or copyright or other Content appearing on the Website are not sponsors of Cabinfield or the Website and have not endorsed and are not affiliated with Cabinfield or the Website, and Cabinfield is not a sponsor and does not endorse any such third parties.</p>
                </article>
                <article class="point-section only-point">
                    <h4 class="heading">No Agency</h4>
                    <p>No agency, partnership, joint venture, employee-employer or franchiser-franchisee relationship is intended or created between you and Cabinfield by this Agreement or as a result of your use of the Website or your purchase of any Products.</p>
                </article>
                <article class="point-section only-point">
                    <h4 class="heading">Notices</h4>
                    <p>All notices hereunder shall be given by certified mail, postage prepaid and return receipt requested, to: Cabinfield LLC, Attn: Legal Department, 15 Cabinfield Circle, Lakewood, NJ 08701 and by email to e-mail at <a href="mailto:service@cabinfield.com">service@cabinfield.com</a>, and to a Registrant at the address and email listed provided to us by such Registrant. Notice shall be deemed given three (3) days after the date of such mailing and upon receipt of such email.</p>
                </article>
                <article class="point-section only-point">
                    <h4 class="heading">Governing Law; Arbitration; <span class="uppercase">No Class claims; Timely filing of claims</span></h4>
                    <p>This Agreement shall be governed by and construed in accordance with the laws of the State of New Jersey, excluding New Jersey’s choice-of-law principles. Any dispute arising out of or relating to this Agreement, including without limitation regarding any breach hereunder (other than for claims qualifying for small claims court, as described below), shall be finally resolved by binding arbitration administered by the American Arbitration Association under its Commercial Arbitration Rules, and judgment upon the award rendered by the arbitrator may be entered in any court having jurisdiction. The arbitration will be conducted in Lakewood, New Jersey, by an arbitrator with applicable industry expertise in ecommerce businesses, who shall be named in accordance with such rules. The award of the arbitrator shall be final and binding on you and us, without a right of appeal, and shall be accompanied by a statement of the reasons upon which the award is based, and such statement as well as all information concerning such arbitration proceedings including without limitation all evidence and materials submitted by you and/or us shall be deemed to be confidential information and shall not be made public by either you or us. If either party sues the other party and loses the claim which was the subject of such a suit, then the non-prevailing party shall pay the prevailing party’s costs and expenses, including but not limited to the prevailing party’s reasonable attorneys’ fees. <span class="uppercase">No arbitration or claim under this agreement shall be joined to any other arbitration or claim, and no class arbitration proceedings shall be permitted</span>. Notwithstanding the foregoing, claims or other disputes which are under the total value of Five Thousand Dollars ($5,000), shall be finally resolved in the Special Civil Part of the Civil Division (otherwise known as small claims court) in Ocean Superior Court located in Ocean County, NJ. Moreover, and notwithstanding the arbitration requirement above, we may apply to any court of competent jurisdiction for injunctive relief or enforcement of the above arbitration provision, without breach of such arbitration provision. <span class="uppercase">You agree that regardless of any statute or law to the contrary, any claim that you may have against any of the cabinfield parties which arises out of or is related to this agreement or otherwise your use of the website or purchase of any products must be filed by you pursuant to this section 15 within one (1) year after such claim or cause of action arose or is claimed to have arisen.</span></p>
                </article>
                <article class="point-section only-point">
                    <h4 class="heading">Assignment</h4>
                    <p>You shall not resell or assign any of your rights, duties or obligations under this Agreement and any attempted assignment or delegation will be void and of no force or effect whatsoever. This Agreement may be automatically assigned by Cabinfield, in our sole discretion, to a third party, and such an assignment will inure to the benefit of our successors, assigns and/or licensees. Without limitation of the foregoing, we may sell, transfer or otherwise share some or all of our assets, including without limitation your PII, with any parent company, subsidiary, joint venture, and a company under our common control, as well as with a potential acquirer, including without limitation in connection with a merger, reorganization, or sale of assets, or in the event of bankruptcy. In each such an event, the PII we have collected from you may be one of the assets transferred.</p>
                </article>
                <article class="point-section only-point">
                    <h4 class="heading">No Waiver</h4>
                    <p>Our failure to act with respect to a breach by you or others does not waive our right to act with respect to a subsequent or similar breach or breaches. If Cabinfield does not exercise or enforce any legal right or remedy which is contained in this Agreement (or which Cabinfield has the benefit of under any applicable law or regulation), such action or inaction shall not be taken to be a formal waiver of Cabinfield’s rights, and all such rights or remedies shall still be available to Cabinfield.</p>
                </article>
                <article class="point-section only-point">
                    <h4 class="heading">General</h4>
                    <p>If any provision of this Agreement is held to be invalid by a court having competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of this Agreement, which shall remain in full force and effect. Section headings are for reference purposes only and in no way define, limit, construe or describe the scope or extent of such section. This Agreement and any ancillary terms and conditions referenced on the Website or otherwise provided by us sets forth the entire understanding and agreement between us with respect to your use of the Website and purchase of Products. The provisions of this Agreement shall survive termination or expiration to the extent necessary to carry out the obligations of you and Cabinfield under this Agreement.</p>
                </article>
                <article class="point-section only-point">
                    <h4 class="heading">Contact Us</h4>
                    <p>If you have any questions or concerns regarding the Website, please contact us by e-mail at <a href="mailto:service@cabinfield.com">service@cabinfield.com</a> or write to us at Cabinfield LLC, 15 Cabinfield Circle, Lakewood, NJ 08701.</p>
                </article>
            </section>
            <!-- .main-content  -->
        </div>
    </div>
</div>
<!-- .page-content ends  -->

<!-- include footer  -->
<?php include_once('sections/layouts/footer.php') ?>