<?php 
// dynamic page title
$page_title="Terms of Use - V3";

// include the header 
include_once('sections/layouts/header.php') 
?>

<!-- .breadcrumb-section starts  -->
<div class="breadcrumb-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12 breadcrumb-area">
                <ol class="breadcrumb dark">
                    <li><a href="home.php"><i class="fa-solid fa-house"></i></a></li>
                    <li><a href="#">Help Center</a></li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- .breadcrumb-section ends  -->

<!-- .page-content starts  -->
<div class="section clearfix page-content">
    <div class="container">
        <!-- .page tittle  -->
        <div class="row">
            <header class="col-md-12 text-dark-color section-title small mb-4">
                <h1>Help Center</h1>
            </header>
        </div>
         <!-- .page tittle ends  -->
         
         
        <div class="row">
            <!-- sidebar starts  -->
            <aside class="col-md-3 page-sidebar">
                <div class="card">
                    <div class="card-body shadow">
                        <ul class="page-list">
                            <li class="active"><a href="terms-of-use.php">Terms of Use</a></li>
                            <li><a href="privacy-policy.php">Privacy Policy</a></li>
                            <li><a href="warranty.php">Warranty</a></li>
                            <li><a href="#">Cancellations/Returns</a></li>
                            <li><a href="#">Shipping & Delivery</a></li>
                            <li><a href="#">Gazebos & Playsets</a></li>
                        </ul>
                    </div>
                </div>
            </aside>
            <!-- sidebar ends  -->
            
            <!-- .main-content  -->
            <section class="col-md-9 main-content mb-5">
                <div class="article-title">
                    <h3>Terms of Use</h3>
                </div>
                <article class="sub-article">
                    <h4>Last Updated: August 14, 2023</h4>
                    <p>Welcome to www.cabinfield.com, an ecommerce website for the purchase of classic Amish crafted furniture and other products (the "Website"). We are happy you have chosen to visit us! The Website is operated by Cabinfield Woodworking LLC, a New Jersey limited liability company with an address at 15 Cabinfield Circle, Lakewood, NJ 08701 (“Cabinfield”, “we”, “our”, or “us”). Anonymous visitors to the Website ("Visitors") can browse our content. Visitors who are at least eighteen (18) years of age and not a minor in their state or residence, and who affirmatively indicate their agreement to abide by these Terms of Use (this “Agreement”) by means of a click-through consent (if and where this option is made available by Cabinfield) (“Registrants”) can purchase any of products and/or services offered through the Website or otherwise by us (collectively, “Products”) and can use additional Website functionality. The term Products also includes standard orders or custom orders. The terms “you”, "your" and “yours” when used in this Agreement refer to either Registrants or Visitors, or to both Registrants and Visitors together, as applicable; provided that such terms will refer to both Registrants and Visitors together unless the context of this Agreement indicates otherwise. This Agreement sets forth the terms and conditions which govern your use of the Website.</p>
                </article>
                <article class="point-section only-point">
                    <h4 class="heading">Electronic Acceptance/Clickwrap</h4>
                    <p>You agree that by clicking a simple button to accept the Agreement you agree to all the terms and conditions. You understand that under the U.S. federal Electronic Signatures in Global and National Commerce Act (“<u>ESIGN</u>”), clickwrap agreements, such as this Agreement that simply requires you to click a box to accept its terms, holds the same status as “wet ink” signatures. The signing of this Agreement by clicking the box, signifies your acceptance of the terms and conditions as specified herein. It also signifies that you are over eighteen (18) years of age and have the authority to enter into such this Agreement.</p>
                </article>
                
                <article class="point-section only-point">
                    <h4 class="heading">Orders</h4>
                    <p>You may purchase the Products through the Website following the procedures for Standard Orders or Custom Orders as explained below. We offer you many different Product options (e.g., model, size, color, finish) which you can select in ordering the Products through the Website (each, a “Standard Order” and collectively, “Standard Orders”). Alternatively, you may create a custom order of the Products (or your own conceived product that we agree to produce) by selecting options beyond those offered through the Website (each, a “Custom Order” and collectively, “Custom Orders”). Please be very careful to inspect the details of each order before you confirm, because you understand that your Product will be built exclusively according to the provisions of the applicable Order Confirmation we send you for such order. If you do not receive an Order Confirmation from us after placing a Standard Order or Custom Order, please check your email “Junk” folder to make sure the Order Confirmation has not been routed there. In the even you do not receive any Order Confirmation shortly after placing your order, you agree to contact us immediately in order to notify us of such an issue.</p>
                    
                    <h5 class="point">Standard Orders</h5>
                    <p>To place a standard order, Registrants place such order through our Website. Once received we will send the Registrant an Order Confirmation by email to confirm the order and then it becomes binding.  Registrants agree that any other phone, email, text, regular mail or overnight courier service communications you send us are not binding. The details we send you in the Order Confirmation email from us to you are binding. Registrants agree to carefully review the Order Confirmation we sent them, and Registrants agree that we are not bound by any prior or subsequent requests, changes, or modifications made by phone, email, text, or regular mail and you agree you may not revise your standard order without our written consent, in our sole discretion, which may include additional fees and a new delivery time.</p>
                    <p>If for some reason you request additional changes after we have sent you the Order Confirmation by email, and we agree to those changes then  a Revised Order Confirmation is sent to you by us via email.  In that situation, the Revised Order Confirmation we send you must be approved by you by a return email of acceptance. Such additional requested changes to revise your standard order may only be approved in our sole discretion, which may include additional fees and a new delivery time. Depending on the type of change, we may at our discretion elect to charge a Change Fee of the greater of $200 or 5% of the order or such greater amount as may be required based on the type of change requested.  If we elect not to make the change to the order, then the Registrant may elect to cancel the order according to the terms outlined below in our cancellation policy.</p>
                    
                    <h5 class="point">Custom Orders</h5>
                    <p>To place a custom order, call us or email us and we will discuss the specifications and requirements you have for a custom order. Once received we will send you an Order Confirmation by email and you must then carefully review that email and then approve it by an email to us. Your affirmative approval of the Order Confirmation will be required in order for us to start processing your order. If you are not in agreement, then call us and we can go over the changes to send you a revised Order Confirmation. Once you place a custom order with us and then you approve by email the Order Confirmation we sent you, we will consider that order binding and it will supersede any discussions on the phone or by email you had with us. Registrants agree that any other phone, email, text, regular mail or overnight courier service communications you send us are not binding. <strong>Only your email confirmation of our Order Confirmation is binding on us. The Registrant must approve the order through that Order Confirmation we send them by email, otherwise we will not process your order</strong> Once we receive approval of that Order Confirmation by email from you to us, the order is binding, and Registrants agree that we are not bound by any subsequent requests, changes, or modifications made by phone, email, text, regular mail or overnight courier service and you agree you may not cancel or revise your custom order without our written consent, in our sole discretion, which may include additional fees and a new delivery time. 		</p>
                    <p>If for some reason you request additional changes after we have received approval of our Order Confirmation from you by email, we will not accept such further changes unless and until we send you a subsequent Order Confirmation and you approve that subsequent Order Confirmation by email to us. Any additional requested changes to revise your standard order without our written consent may only be approved in our sole discretion, which may include additional fees and a new delivery time. Depending on the type of change, we may at our discretion elect to charge a Change Fee of the greater of $200 or 5% of the order or such greater amount as may be required based on the type of change requested.  If we elect not to make the change to the order, then the Registrant may elect to cancel the order according to the terms outlined below in our cancellation policy.</p>
                    
                    <h5 class="point">Acceptance</h5>
                    <p>Please read this Agreement carefully before otherwise accessing the Website to make a purchase.  Prior to making a purchase, you must first agree to be bound by the provisions of this Agreement. You indicate that you have read, understood and agree to be bound by the provisions of these Terms of Use, which together with our Privacy Policy, make a binding agreement (“Agreement”) and you agree to periodically review this Agreement to be aware of such modifications between you and us. Before placing an order, you must show your consent to our Agreement by means of a click-through consent (where provided by us), or as further described above for Standard Orders or in the case of Custom Orders by approving our Order Confirmation by electronic mail. If you do not agree to be bound by this Agreement, you are not authorized to use the Website or otherwise to purchase any Products. You also are not authorized to use the Website if (a) you are not of legal age or otherwise do not have the legal capacity to form a binding contract with Cabinfield, or (b) you are a person barred from using the Website either (i) under the laws of the country in which you reside or from which you are attempting to access the Website, or (ii) due to prior violations of this Agreement. </p>
                    
                    <h5 class="point">Phone Orders</h5>
                    <p>If you place your order by phone, you will receive an email from us with links to our Terms of Service and Privacy Policy which you must agree to by clicking a box. Additionally, you will have to reply to our email after reviewing the order details and specifications and confirm by email to us that the order is correct.  After reviewing that email, if you need additional changes you will need to contact us so we can make changes and send you a revised order by email which will require you to confirm by email to us before we can start building the furniture. All phone orders and changes are subject to our sole approval and will be followed up with a revised Order Confirmation for you to approve.</p>
                </article>
                
                <article class="point-section only-point">
                    <h4 class="heading">Modification</h4>
                    <p>We reserve the right to modify this Agreement at any time. You shall periodically review this Agreement to be aware of such modifications. You further agree that your continued use of the Website after any such modifications have been made shall be deemed to be your conclusive acceptance of any modified version of this Agreement. We will indicate that changes to this Agreement have been made by updating the date indicated after “Last Updated” at the beginning of this Agreement, and any updated supplemental policy or other terms (which are a material part of this Agreement as indicated below) will be indicated in the same manner. We will be happy to provide you with prior versions of this Agreement (including any supplemental policy or other terms) upon your written request to us. If you do not agree to abide by the initial version and each modified version of this Agreement, then you are not authorized to use the Website and agree not to use our Website for any reason. A current version of this Agreement is accessible via the footer of the Website’s homepage.</p>
                    
                    <h5 class="point">Account Registration</h5>
                    <p>A Registrant who registers with us will receive a unique account (“Account”) and will be able to access such Account by selecting a corresponding user ID and password. You shall not allow any individual or entity to use your Account to access the Website or otherwise to contact us and you shall strictly safeguard your user ID and password and any other information that would allow any person to access the Website or otherwise to contact us by using your Account. You are solely responsible for your failure to strictly safeguard such information and/or to allow any other person to access or use the Website or otherwise to contact us by using your Account. You may not sell or otherwise transfer your Account or any portion thereof. You shall notify Cabinfield immediately of any unauthorized use of your Account or any portion of the Website. Cabinfield shall not be liable for any loss that results from the unauthorized use of your Account, either with or without your knowledge.</p>
                    
                    <h5 class="point">Accurate Information</h5>
                    <p>You shall provide accurate, complete and current information about yourself when registering for your Account and otherwise when using the Website, and you shall update all information provided by you through the Website if and as soon as such information changes.</p>
                    
                    <h5 class="point">Disabling or Revoking of Account</h5>
                    <p>We have the right to suspend or terminate your Account at any time if we believe you have violated or are likely to violate this Agreement, all as determined by us in our sole discretion. If we suspend, terminate or otherwise disable access to your Account, you may be prevented from accessing certain portions of the Website, including your Account details and/or any the comments, icons, images, messages, tags, links, photographs, text, audio, video and other like content appearing on the Website (collectively, “Content") which was uploaded or otherwise provided through your Account or otherwise by you to the Website or otherwise to us (collectively, “Your Content”), all of which may be deleted by us. In such a case, your rights to use the Website and access any of Your Content may cease immediately. Suspension or termination by us is without prejudice to all other remedies available to Cabinfield by law or under this Agreement.</p>
                    
                    <h5 class="point">Cessation of Functionality; Change of Products</h5>
                    <p>As part of our continuing innovation, we may stop (permanently or temporarily) providing certain Website features to you in our sole discretion, without prior notice to you. The form and nature of any of the Products may change from time to time without prior notice to you.</p>
                </article>
                
                <article class="point-section only-point">
                    <h4 class="heading">Purchases</h4>
                    <p>All of the Products are acquired by you on a “AS IS” and “WHERE IS” basis. If you wish to purchase any of the Products, you shall comply with the applicable provisions of this Agreement as well as the provisions of any ancillary policies, terms, conditions or agreements which govern your purchase of any of the Products. To the extent we have the authority to do so, we reserve the right (but do not have the obligation) to correct any errors or mistakes made by our ecommerce service provider even if it has already requested or received payment from you, though we are not responsible for errors by our ecommerce gateway or other service providers and any recourse you wish to seek which relates to any such error shall be directly to such service provider. Thus, we may cancel any order that was based on erroneous information (e.g., an incorrect price). Further, we may refuse to sell to you for any reason (as determined by us in our sole discretion) given your past history or otherwise. You will use all Products you purchase for their intended use only.</p>
                    
                    <h5 class="point">Payments</h5>
                    <p>Your submission of a check to us, or your request for us to charge your credit card by providing your credit card information to us or to our ecommerce gateway or other service provider, indicates your express authorization for us (or such third party) to charge your credit card for the associated purchase requested by you. By making a purchase through the Website, you agree to pay us (or our ecommerce gateway or other service provider, as the case may be) all charges at the prices then in effect using the payment method selected by you. Your right to receive any of the Products is conditional on our prior receipt of the full payment and related costs for each such Product. If all such payment and costs cannot be charged to your credit card or if a charge is refunded for any reason, including by chargeback, we reserve the right to refuse to deliver the Product you ordered and/or cancel your order, as determined by us in our sole discretion. Again, you are fully responsible for all charges made under your Account or otherwise in your name, and you will pay us all fees associated with any returned check or other reversal of any purchase by you. Your credit card payment may be rejected if we (or a third party working on our behalf) detect the presence of certain fraud indicators. Whether a credit card is accepted or rejected is not always determined by information provided by the cardholder, and we apologize for any inconvenience for orders where a credit card payment is not possible. For international orders, Cabinfield may, at its sole discretion, require payment by wire transfer, and all such purchases shall be in US Dollars. Please note that there are certain non-refundable deposits which apply to our orders, and this issue is described in detail in our Cancellation and Return Policy set forth below.</p>
                    
                    <h5 class="point">International Users</h5>
                    <p>Our Website is controlled, operated, and administered by us from our offices within the USA. If you access our Website from a location outside the USA, you are responsible for compliance with all local laws. You agree that you will not use our Website in any country or in any manner prohibited by any applicable laws, restrictions or regulations.</p>
                </article>
                
                <article class="point-section only-point">
                    <h4 class="heading">Our Warranty and Disclaimer</h4>
                    <p>Cabinfield Products are crafted to provide enduring beauty and lasting quality. Cabinfield will completely cover costs for any defects in materials and/or workmanship (as determined by Cabinfield in its sole discretion), that occur within one year of purchase. This limited warranty applies to the original purchaser of our Product. The warranty does not cover normal wear and tear, or the natural weathering of wood when exposed to the elements.</p>
                    <p>Our Website is provided "as is", "as available" and "with all faults" and Cabinfield does not warrant its accuracy, completeness, availability, reliability, or timeliness. Cabinfield does its best to keep prices and specifications updated on the Website, but we reserve the right to notify customers of any necessary price adjustments prior to final processing and shipment of an order.</p>
                    <p>You agree to assume the entire risk as to your use of our Website and information provided herein. In addition, and without limiting the foregoing, Cabinfield disclaims any and all warranties with respect to any delays or errors in the transmission or delivery of any materials, Products or services available through our Website.</p>
                    
                    <h5 class="point">Descriptions</h5>
                    <p>We attempt to be fully accurate in describing the Products (including, without limitation, the price of each Product) offered for purchase by us through the Website; however, we do not warrant or represent that all such descriptions are complete, current or error-free. Further, all such descriptions are subject to change at any time (even after a purchase has been effectuated) and without notice, in our sole discretion. We are not responsible for any such errors and we have the right (as exercised by us in our sole discretion) to change or cancel any orders which were made based on any missing or inaccurate information. For clarity, if your order was based on any inaccurate description, we may (as determined by us in our sole discretion) either notify you of any necessary price adjustments prior to final processing and shipment of the order or we may cancel your order and refund you any payments already made by you for such order.</p>
                    
                    <h5 class="point">Color</h5>
                    <p>With regard to the staining of wood, you acknowledge and understand that wood is an organic material and colors stain in different ways (even the same color with the same type of wood has variations) given the different grades of natural wood and other variables involved in creating each Product. Thus, we cannot guarantee any uniform color palette for any of the Products, and the colors we offer usually fall within a certain range or tones. If you are especially concerned about a particular color for a Product you wish to order, then we suggest you request us to send you a stain sample or samples to help you decide on the stain that will work best for you. For an additional fee, we undertake additional efforts to match the sample sent to you (we call this additional service a “stain match”), and often these efforts do result in a closer color match. But please note that even if we have undertaken a “stain match” for the Product ordered by you, we cannot guarantee a precise shade of stain for that Product. While our samples are excellent approximations, they may vary from the actual stain on the Product you receive (again, these variations occur naturally as a result of differences in wood grain, type of wood, stain composition, and other naturally occurring factors). Thus, we cannot be and are not responsible for any differences between the sample color and the final color of the stain you choose for your ordered Product. We provide these stain samples with a refundable deposit if you return the samples (and you pay the shipping costs) within thirty (30) calendar days.</p>
                </article>

                <article class="point-section">
                    <h4 class="heading">Shipping and Delivery Policy.</h4>
                    <h5 class="point">1. Delivery Methods and Obligations</h5>
                    <p>We understand that the process of moving large indoor and outdoor furniture can be challenging, and we work hard to find the best option that will minimize shipping costs and maximize your convenience. The shipping methods we use depend on the type of furniture, destination and other factors. Although we do try to minimize shipping costs, please keep in mind that packing furniture for safe transportation and delivery can be expensive; however, proper care in the shipping process is critical to protect your investment in each of our Products. To facilitate a safe and easy motor freight delivery of your Product(s), you must ensure that (i) someone eighteen (18) years of age or older (and not a minor in the State of delivery location) is available to accept delivery, (ii) all obstacles (including without limitation snow) which may hinder delivery is removed or otherwise remedied, and (iii) the location in which you want your Product(s) placed is cleared of all other items and ready for delivery (i.e., we are not responsible for moving or removing any existing items to make space for your Product(s)). Please note that if you are not at the delivery address at the agreed time for delivery or if you for any reason refuse delivery, you will incur a re-delivery charge from the shipper (note that Cabinfield has no control over the policies of third party shippers). If you are shipping to a remote area or hard to access location, then additional fees may apply. We will charge credit card on file for any transaction or like fees or expenses. </p>
                    
                    <p><strong>Remote Areas:</strong> Remote areas and hard to access locations are defined as addresses in remote areas in the country, locations on islands, or those delivery addresses only accessible by ferry or where access is limited to specific time schedules. An example of this would be Martha's Vinyard.  Prior to placing your order, please be upfront with us if you are in a remote area because there will be an extra cost associated with your delivery and standard delivery charges do not apply.</p>
                    <p><strong>Certificate of Insurance:</strong> You agree that if a certificate of insurance (“COI”) is required any COI fees are extra. A COI is sometimes required by a building prior to allowing a business to deliver or perform a service there. It is specific to the building and tenant and must meet the building's liability limit requirements, list their specific certificate holders and contain various other specifics, thus each COI must be custom generated by our insurance department for each customer. Some require very high levels of liability or umbrella policies that we will not incur the expense to carry, and we again will offer curbside delivery to a 3rd party facilitator who, for an additional expense, will deliver to the building (these cases, of course, would not necessitate a COI fee). Most, though not all, COIs are required by buildings in the New York City area. Before you place your order, please let us know if you reside in an apartment building or condominium complex and if a COI is required, and provide us with a sample COI from your building management. In the event we are given less than 5 business days' notice of the need for a COI, your delivery will be delayed to allow time to process your COI.</p>
                   
                    <h5 class="point">2. Delivery Time</h5>
                    <p>Under normal circumstances, most of our Products customarily have been ready to ship within eight (8) weeks of placing your order, though delays due to a pandemic, acts of war, riots, sever weather, strikes, and supply chain issues can increase this “lead” time to a range of twelve (12) to fourteen (14) weeks. However, even these estimated times are variable and will change due to the volume of orders at any given time or other factors beyond our control. If you need to have your Product(s) delivered by certain time, you must indicate this clearly at the time of your order and we will try to determine whether we believe it will be realistic to meet such a deadline, but even then, we cannot guaranty delivery by any certain date. We are able to ship some of the Products labeled on our Website as “QuickShip” using shorter lead times, but again we cannot guarantee any specific delivery date and we are not responsible for any delays.  Gazebos and Playsets may be available for shipping sooner, and customarily take approximately three (3) to six (6) weeks to be ready for shipping. You acknowledge that we cannot guarantee that any Products you order will be delivered within any specific timeframe. In the event that we expect delivery delays on particular pieces, you will be notified as soon as we learn of such delays. Despite our efforts, we may encounter circumstances beyond our control, and we may not meet our projected delivery schedule. For instance, to ensure the safety of customers and shippers, we reserve the right to delay deliveries due to hazardous road and/or weather conditions. In the occasions where delays may occur, we will do our very best to fill your order as expeditiously as possible, but we cannot guarantee an exact delivery date and are not responsible for monetary losses that may result from such unexpected delays. Unless otherwise determined by us, we will notify you by email (to your email of record) when the Product(s) you have ordered are ready to ship.</p>
                    <h5 class="point">3. Indoor Furniture</h5>
                    <p>Our indoor furniture Products are typically delivered by a network of private shippers, and the shipper will be in touch with you to arrange a date and time for delivery. We offer two options for the delivery of our indoor furniture Products, curbside delivery and indoor delivery, as follows:</p>
                    <p>(a) <u>Standard Curbside Delivery:</u> The shipper will unload your Product(s) off the truck and place it on the sidewalk or otherwise in front of the delivery premises. This option is the least costly and is most often selected by our customers. If you select this delivery option, it will be your responsibility to inspect the Product(s) in the location (and note any issues in writing <u>before</u> signing to accept the delivery) it is placed and to move it onwards from such a location. Please note that the driver is an employee of the shipping company and not of Cabinfield. The driver may leave once the shipment is off the truck and you sign to accept delivery. The driver is not required to assist you in bringing the item into your home.</p>
                    
                    <p>(b) <u>Indoor Delivery and Setup:</u> For an additional fee, Cabinfield offers an indoor delivery and setup option where the shipper will take care of the entire unloading and set-up process. Please be sure the furniture will fit in the desired room and through all entryways and hallways within a comfortable margin. We are not responsible for any damage that may result from limited maneuverability due to narrow halls, stairwells, doors, etc. In the event that setup in your desired area is not feasible, the delivery and setup will occur in the closest reasonably accessible area in the delivery premises. If the Product(s) will need to be taken up more than one flight of stairs, <u>you must notify us of this in writing</u> before delivery occurs.</p>
                    
                    <h5 class="point">4. Outdoor Furniture</h5>
                    <p>While many of our outdoor Products are small enough to be shipped via UPS or FedEx, our larger outdoor patio furniture Products as well as our outdoor structures are delivered by motor freight. If the delivery location is not accessible by delivery truck (e.g., the truck is too large to enter your street), we will transport your furniture to the nearest reasonably accessible point, and it will be your responsibility to inspect and move the Product(s) at and from that location. When a Product(s) is delivered by common carrier motor freight, it will be your responsibility to move the Product(s) from the rear of the truck. You will need to make accommodations to assist the driver with unloading, and although most drivers are very accommodating and will help with the unloading (usually for a nominal additional fee), we cannot guarantee that your driver will be willing to provide such a service.</p>
                    
                    <h5 class="point">5. Inspection of Delivered Products</h5>
                    <p>For clarity and notwithstanding anything stated herein to the contrary, you are exclusively responsible for inspecting each Product(s) delivered at the time of delivery (<u>and before the driver has left the premises</u>) to make sure that it is in perfect condition. If you notice any issue and in order to obligate Cabinfield to remedy any damage or defects, you must note all such issues with specificity on the delivery confirmation sheet you sign and then immediately contact us. If you have any additional questions concerning shipment of your order, please call us at 866-450-9663 (WOOD).</p>
                    <h5 class="point">6. Delays by You</h5>
                    <p>In the event that you communicate to us (directly or through a lack of responsiveness) that you are unable to accept the Product(s) you have ordered once your order is ready to ship, Cabinfield will hold the Product(s) for you, free of charge (as a courtesy), for a maximum period of four (4) weeks. After that four (4) week period has elapsed, unless other arrangements have been made and confirmed in writing (including by email) by Cabinfield, Cabinfield shall arrange for the continued storage of such Product(s) at your sole risk and expense. This may include, and you will be liable for, any and all fees and costs arising from such delay, including without limitation all of our own and all third-party fees and costs relating to storage, insurance, transport and other handling of such Product(s). If not otherwise agreed in writing by you and us, the costs for storage shall be the greater of (a) Two Hundred Fifty Dollars ($250) per month, or (b) five percent 5% of full invoice amount of the order for such Product(s) per month. Further, in the event that you do not arrange for delivery of the Product(s) within three (3) months of the originally scheduled delivery date, then Cabinfield shall be entitled (as determined by Cabinfield in its sole discretion) to (a) continue storing the Product(s) at your sole expense, or (b) resell or otherwise determine the use of any or all of the Product(s) ordered by you; provided, however, that Cabinfield will endeavor to give you no less than fourteen (14) calendar days advance written notification of our decision to resell or otherwise use the Product(s). For the sake of clarity, in any such circumstance Cabinfield shall also keep the full amount of any deposit already paid by you.</p>
                </article>
                
                <article class="point-section only-point">
                    <h4 class="heading">Additional Warranty on Gazebos & Playsets</h4>
                    <p>We warranty the wood and construction of our Gazebo & Playsets products against damage from rot and/or termites - for as long as you live in your home. We reserve the right to remedy any defect that may occur in your Product, and we will typically do that through our network of qualified independent contractors. To qualify for this additional warranty, you: (1) must have performed normal maintenance on the Product, as determined by Cabinfield (and as provided in the Buyer's Guide, described below), and (2) must not use the Product for commercial purposes or in a commercial establishment (unless you specifically purchased a Commercial Gazebo, in which case commercial use is expected and the additional warranty will apply). Some parts, such as roofing, have additional warranties from their manufacturer.</p>
                    <p>As is the case with any wooden product, performance and beauty depends on how well you maintain and care for it. Please see our Buyer's Guide for suggested gazebo maintenance. The natural properties of wood include knots, minor cracks, splinters, and natural expansion and contraction of lumber depending upon temperature, environment, and natural grain traits. Adhering to our maintenance schedule will maximize the performance and beauty of your natural wooden gazebo. This warranty excludes damage due to ground settlement, modification, or any abnormal conditions out of our control.</p>
                    <p>For those who wish to have a virtually maintenance-free gazebo experience, Cabinfield offers a number of high-quality, affordably priced vinyl gazebos. These gazebos require almost no maintenance and will last for many years to come. If you want to have the look of a gazebo but don't have the time to properly maintain fine wooden products, our vinyl option is the perfect solution. We provide a 10 year warranty on our vinyl gazebos against any material or manufacturing defects.</p>
                </article>


                <article class="point-section">
                    <h4 class="heading">Reservation of Rights</h4>
                    <h5 class="point">Modifications</h5>
                    <p>The raw materials of some of the Products may have limited quantities and we cannot guarantee the availability of any Product. We reserve the right, but are not obligated, to limit or discontinue the sale of any of the Products to any person (including without limitation the quantity of any specific of the Products), geographic region or jurisdiction, or otherwise, and we may exercise this right on a case-by-case basis in our sole discretion. The offer of any of the Products made through our Website or otherwise is void where prohibited. We further reserve the right to limit or prohibit orders of any of the Products that, in our sole judgment, appear to be placed by persons who are dealers, resellers or distributors, whether or not they have so identified themselves to us.</p>
                    <h5 class="point">Taxes</h5>
                    <p>You are responsible for paying all applicable taxes arising out of any purchase of any of the Products made by you through the Website or otherwise, including without limitation all duties, taxes, and/or other fees that may apply to the import of any Products.</p>
                    <h5 class="point">Your Personal Information</h5>
                    <p>In the event you wish to purchase any of the Products or use other certain functionality of the Website, you will be asked by Cabinfield and/or a third party working on our behalf to supply certain of your personally identifiable information (“PII”). You shall provide us and/or such third party (as applicable) with accurate, complete and current PII (including without limitation your email address and credit card number and expiration date which are used by our third party processor to process your payment), and you shall update all PII if and as soon as such information changes before you make any additional purchase of any the Products. You shall be responsible for all activity conducted through the Website which is identified with such information.</p>
                    

                    <h5 class="point">Your Content: Usage Restrictions</h5>
                    <p>You shall adhere to following terms and conditions for using the Website: (a) Cabinfield has no obligation to use or respond to any of Your Content, (b) the provision of Your Content to us in no way imposes any obligation on Cabinfield, whether of confidentiality, attribution, compensation or otherwise, and Cabinfield shall not be liable for any disclosure or other use of any of Your Content, (c) all Your Content shall be accurate and shall not violate the copyright, trademark, patent, trade secret, right of publicity, right to privacy, or any other intellectual property or other legal right of any third party, (d) you shall pay for all royalties, fees and any other monies owing any person by reason of any of Your Content that you post to the Website and you shall hold us harmless and indemnify us from any and all such claims, (e) Your Content may be subject to size and usage limitations, and you are responsible for adhering to any such limitations, and (f) all of Your Content shall comply with all other applicable sections of this Agreement.</p>
                    <h5 class="point">Quality and Review of Your Content</h5>
                    <p>We do not and shall not have any obligation to review Your Content, and therefore we do not guarantee the accuracy, integrity or quality of any of Your Content or the Content of any other person or entity, and thus we cannot assure that harmful, inaccurate, deceptive, offensive, threatening, defamatory, unlawful or otherwise objectionable Content will not appear on the Website. Notwithstanding the foregoing or anything to the contrary in this Agreement, Cabinfield (a) has the absolute right (but not the obligation) to pre-screen, monitor, review, flag, filter and remove any and all of Your Content in our sole discretion, and we reserve the right to alter, edit, refuse to post or remove any of Your Content, in whole or in part, for any reason or for no reason as determined by us in our sole discretion, and (b) has the right to disclose Your Content and the circumstances surrounding its transmission to any third party in order to satisfy any applicable law, regulation, legal process or governmental request or to protect ourselves, other Website users or service providers or any other person, as determined by us in our sole discretion.</p>
                    
                    <h5 class="point">Usage Restrictions</h5>
                    <p>You shall not use the Website in any manner that:</p>
                    <ol class="alpha">
                        <li>enables you (or enables any other person) to (i) copy, modify, create a derivative work of, any Content, or (ii) copy, modify, create a derivative work of, reverse engineer, translate, adapt or decompile (or attempt to translate, adapt or decompile) or otherwise attempt to extract any software underlying any portion of the Website or the source code of the software underlying the Website or any portion thereof; </li>
                        <li>interferes with operations or services provided by the Website or otherwise disrupts the Website in any way; </li>
                        <li>interrupts, destroys or limits the functionality of, any computer software or hardware or telecommunications equipment (including without limitation by means of software viruses, Trojan horses or any other computer code, files or programs); </li>
                        <li>infringes any copyright, trademark, trade secret, patent or other right of any party (including the promoting of an illegal or unauthorized copy of another person's copyrighted work), or defames or invades the publicity rights or the privacy of any person, living or deceased (or impersonates any such person);</li>
                        <li>is false, misleading, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, hateful, or racially, ethnically or otherwise objectionable, as determined by us in our sole discretion;</li>
                        <li>creates a false identity or otherwise attempts to mislead any person as to the identity or origin of any communication;</li>
                        <li>exports, re-exports, or permits downloading of any message or content in violation of any export or import law, regulation, or restriction of the United States and its agencies and authorities, or without all required approvals, licenses, or exemptions;</li>
                        <li>causes us to lose (in whole or part) the services of our internet service providers or other suppliers;</li>
                        <li>consists of any unsolicited or unauthorized advertising, promotional materials, “junk mail,” “spam,” “chain letters,” “pyramid schemes,” or any other form of solicitation;</li>
                        <li>links to materials or other content, directly or indirectly, to which you do not have a right to link or which we determine in our sole discretion is not appropriate to be linked to from the Website; or</li>
                        <li>violates, or encourages others to violate this Agreement (or engages in any other activity deemed by us to be in conflict with this Agreement), or violates or encourages others to violate any applicable local, state, national, or international law.</li>
                    </ol>
                    <h5 class="point">Reporting Violations</h5>
                    <p>You shall immediately notify us in writing of any of Your Content or of any other Content that you view through the Website which you deem to be offensive, inappropriate or otherwise a violation of this Agreement.</p>
                    <h5 class="point">Disabling or Revocation of Use</h5>
                    <p>We have the right to cancel or suspend your use of the Website (if applicable) including without limitation any purchase made by you, for any reason (without having to specify the reason) or for no reason at any time, as determined in our sole discretion, including without limitation if we believe you have violated this Agreement.</p>
                </article>
                
                <article class="point-section only-point">
                    <h4 class="heading">Intellectual Property, Proprietary Rights</h4>
                    <p>Content provided by Cabinfield or any of our third party licensors is protected by copyright, trademark and other laws of the United States and/or other jurisdictions. Other than for Your Content and third party Trademarks (as that term is defined below in the section entitled Trademarks) appearing on the Website, you acknowledge and agree that as between you and us, all right, title and interest (including without limitation all copyright, trademark, patent, trade secret and other intellectual property rights) in and to Website (including without limitation all other Content appearing therein) is owned by us, and that you have no rights in and to the Website other than as expressly set forth in this Agreement. Except for that information which is in the public domain and is not otherwise limited by third party rights or for which you have been given express written permission by us, no Content (other than for Your Content as uploaded by you to the Website alone) may be sold, copied, reproduced, republished, uploaded, displayed, posted, transmitted, distributed, modified, publicly performed, used in any derivative works based thereon or otherwise used for any public or commercial purpose without our prior written consent or, where applicable, that of our licensors. However, you may print copies of materials on the Website for your personal, noncommercial use only, provided that you must keep intact all copyright, Trademark, and other proprietary notices appearing therein and that you use such materials only in the manner permitted by this Agreement and never in any manner which directly or indirectly competes with us. For clarity and without limiting the foregoing, please note that Content posted by other Website users may also be protected by copyright, trademark patent and other rights under the laws of the United States and/or other jurisdictions, and no rights in such Content whatsoever are granted to you other than those expressly granted herein or by the owner of such Content.</p>
                    <h5 class="point">Grant of License to Your Content</h5>
                    <p>By posting Your Content to the Website, you automatically grant, and represent and warrant that you have the right to grant to Cabinfield, a non-exclusive, perpetual, irrevocable, sub-licensable (through multiple tiers), assignable, fully-paid, royalty-free, and worldwide license to use, copy, modify, adapt, publish, make, sell, publicly display, create derivative works of or incorporate into other works all of such Your Content (in whole or in part), communicate to the public, distribute (through multiple tiers), perform or display Your Content (in whole or in part), in any form, media, or technology now known or later developed, and to grant and authorize sublicenses of the foregoing through multiple tiers of sub-licensees, including the right to exercise the copyright, publicity, and any other rights over any of the materials contained in Your Content for any purpose, including without limitation for purposes of advertising and publicity on the Website and elsewhere, and/or otherwise to generate any revenue. We shall not be limited in any way in the use, commercial or otherwise, of any of Your Content, and you hereby waive any moral rights (or “droit moral”) in, or approval rights to, Your Content. For clarity and without limiting the foregoing, we reserve the express right to incorporate any of Your Content into any further work, in any medium now or hereafter known, without prior consent or review, and without attribution or payment of any royalty or fee whatsoever.</p>
                    <h5 class="point">Copyright Agent</h5>
                    <p>The Digital Millennium Copyright Act of 1998 (the "DMCA") provides recourse for copyright owners who believe that material appearing on the Internet infringes their rights under U.S. copyright law. If you believe that your work has been copied and posted on the Website in a way that constitutes copyright infringement, please provide our copyright agent with the following information: (a) an electronic or physical signature of the copyright owner or of the person authorized to act on behalf of the owner of the copyright interest, (b) a description of the copyrighted work that you claim has been infringed, (c) a description of where the material that you claim is infringing is located on the Website, (d) your address, telephone number, and e-mail address, (e) a written statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law, and (f) a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf. Any notification by a copyright owner or a person authorized to act on its behalf that fails to comply with requirements of the DMCA shall not be considered sufficient notice and shall not be deemed to confer upon us actual knowledge of facts or circumstances from which infringing material or acts are evident. Our copyright agent for notice of claims of copyright infringement can be reached as follows:</p>
                    <address>
                        <p>Name: Cabinfield LLC Copyright Agent<br>
                            Address: 15 Cabinfield Circle, Lakewood, NJ 08701<br>
                            Telephone: 	866-450-9663<br>
                            Email: <a href="mailto:service@cabinfield.com">service@cabinfield.com</a></p>
                    </address>
                    <p>We suggest that you consult your legal advisor before filing a notice with our copyright agent. You should note that there can be penalties for false claims under the DMCA. We will, in appropriate circumstances and to the extent plausible, terminate the right of Website users who infringe the rights of copyright holders to interact with certain portions of the Website.</p>
                    <h5 class="point">Trademarks</h5>
                    <p>“CABINFIELD” is a Trademark of Cabinfield. All other Trademarks referenced on the Website are the property of their respective owners. Cabinfield is not affiliated with or sponsored or endorsed by any trademark owner whose Trademark may appear on the Website and whose owner is not indicated to be Cabinfield. As used herein, the term “Trademarks” means, collectively, all service names, graphics, designs, logos, page headers, button icons, scripts, commercial markings, and trade dress appearing on the Website which indicate a source of goods or services. Trademarks are protected by the trademark laws of the United States and/or other jurisdictions. You may not use, copy, reproduce, republish, distribute or modify any Trademarks in any way, including without limitation in the distribution of any Content, for advertising or publicity or otherwise, without our prior written consent or the prior written consent of each such third party Trademark holder, as applicable. Unless you have been expressly authorized to do so in writing by Cabinfield or any other applicable Trademark holder, you shall not use any Trademark in any way that is likely or intended to cause confusion with the owner of such Trademark.</p>
                    
                    <h5 class="point">Removal of Notices</h5>
                    <p>You shall not remove, obscure, or alter any proprietary rights or notices (including without limitation copyright and Trademark notices) which may be affixed to or contained within any Content. You shall abide by all such notices.</p>
                    <h5 class="point">Links; Third Party Websites</h5>
                    <p>The Website may provide links to third party websites that we believe may be of potential interest to you. Because we do not endorse or otherwise have control over such websites, we are not responsible or liable, directly or indirectly, for (a) the availability of such websites, (b) any content, data, text, software, music, sound, photographs, video, messages, tags, links, advertising, services, products, or other materials on or available from such websites, (c) your participation, correspondence or business dealings with any third party regarding payment and delivery of specific goods and services, and any other terms, conditions, representations or warranties associated with such dealings, which are solely between you and any such third party, and (d) any damage or loss caused or alleged to be caused by or in connection with your interaction with any such third party or any other third party whom you form a connection with through or because of the Website. Your use of any website linked to from the Website is subject to the policies and procedures of the owner of such website and not to the terms and conditions of this Agreement. You agree to hold us harmless from any claims of loss as a result of your use of such third party websites.</p>
                    <h5 class="point">Warranty</h5>
                    <p>Cabinfield products are crafted to provide enduring beauty and lasting quality. Cabinfield will completely cover costs for any defects in materials and/or workmanship (as determined by Cabinfield in its sole discretion), that occur within one year of purchase. This limited warranty applies to the original purchaser of our product. The warranty does not cover normal wear and tear, or the natural weathering of wood when exposed to the elements.</p>
                    
                    <h5 class="point">WARRANTY DISCLAIMER</h5>
                    <p>The Website of Cabinfield.com is provided "as is", "as available" and "with all faults" and Cabinfield does not warrant its accuracy, completeness, availability, reliability, or timeliness. Cabinfield does its best to keep prices and specifications updated on the Website, but we reserve the right to notify customers of any necessary price adjustments prior to final processing and shipment of an order.</p>
                    <p>You agree to assume the entire risk as to your use of our Website and the information provided on our Website by us or others. In addition, and without limiting the foregoing, Cabinfield disclaims any and all warranties with respect to any delays or errors in the transmission or delivery of any materials, Products or services available through Cabinfield's Website.</p>
                </article>
                
                <article class="point-section only-point">    
                    <h4 class="heading">Cancellation and Return Policy. </h4>
                    <ol>
                        <li>We Strive for Your Satisfaction. We want you to be satisfied with each purchase of our Products, and we always strive hard to meet this goal. At Cabinfield, we understand that there may be times when you may wish to return your purchase, and we want to make sure that when we offer such an option the return process is as smooth as possible. </li>
                        <li>Cancellations. While we would like to have as generous a cancellation and return policy as possible, a lot of effort goes into the making of our Products and thus we are only able to permit cancellations and returns in limited circumstances. And we have different cancellation policies for each type of our Products ordered through a Standard Order or a Custom Order, which cancellation policies are as follows:
                            <ol class="alpha mt-2">
                                <li>Cancellations of Standard Orders. All Standard Orders may be canceled within one (1) business day from the date of your order, free of charge and without any penalty. After this initial one (1) day grace period, we enable you to cancel a Standard Order but we will deduct from your refund the credit card charges and fees involved in your initial charge and in the refund being credited to your account. After three (3) days, we will enable you to cancel such an order, but we will deduct from your refund fifteen percent (15%) of the order’s total value, as well as all credit card charges and fees involved in your initial charge and in refunding your account. In order to cancel an order, you must contact Cabinfield directly to make any cancellation request and to inquire about whether work has commenced on your order. If your Standard Order has been delivered and you want to return it to us, you may do so, but we will charge you the above refund amount and additionally you are solely responsible for paying for all shipping and insurance costs in returning the Product to us.</li>
                                <li>Cancellation of Custom Orders. A Custom Order may be cancelled only before production has started, but because of the time involved in generating such an order we will deduct from your refund an administrative fee equal to twenty percent (20%) of the order’s total value. And once production for a Custom Order has started, the order may not be cancelled. <strong>So please be VERY sure and especially careful of what appears in your written confirmation of each Custom Order, because your ability to cancel such an order is very limited</strong>. Please note that all Gazebo & Playset orders are automatically considered to be Custom Orders (even if only the options offered on the Website are selected) and will be billed accordingly.</li>
                                <li>To Obtain Authorization. To initiate a permitted cancellation according to the above parameters, please call us toll-free at 866-450-WOOD (9663) or send an e-mail to: <a href="mailto:service@cabinfield.com">service@cabinfield.com</a>, and if you are eligible, we will provide you with an authorization and further information about how to process a cancellation.</li>
                            </ol>
                        </li>
                        <li>Returns. In the unlikely event that your Product is received in a damaged condition, or with a manufacturing defect, or was not built according to the specifications in the Order Confirmation, rest assured that we will  do our best to make it right. To qualify for our damage-return policy (which waives the above refund fee and shipping costs), <u>you are exclusively responsible for inspecting each Product delivered at the time of delivery, and before the driver has left the location, to make sure that it is in new and good condition, and if you notice any issue you must record the damage at the time of delivery in writing with the shipper (on the delivery confirmation sheet you sign) and then immediately contact Cabinfield by email at <a href="mailto:service@cabinfield.com">service@cabinfield.com</a> or by phone at 866-450-9663 (WOOD)</u>. If you fail to notify us before the driver has left, we can no longer go back to the shipper who caused the damage. Depending on the severity of the damage, and only if you have complied with the foregoing steps, we will either repair your item or replace it free of charge, as determined by us in our reasonable sole discretion. <br/> <br/>If the Product was not built according to the specifications in the Order Confirmation, and only if you have complied with the foregoing steps, we will either repair your item or replace it free of charge, as determined by us in our reasonable sole discretion. With regard to Standard Orders, Custom Orders, or Product modifications, if we built your furniture according to the Order Confirmation and the specifications on the website listed for the product,  you agree that the return policy does not apply. For instance, a Standard Order involves picking a stain. The stain color may end up being slightly different than you may expect even though we use the wood and stain specified. That is because the exact look depends on the grain of the wood etc.  Should you need an exact match of a stain to your existing furniture, we usually can for a reasonable charge, if you send us a sample to match to, provide a Stain Match.  This must be requested together with your order.</li>
                    </ol>

                </article>
                <article class="point-section only-point">
                    <h4 class="heading">Representations, Warranties and Covenants</h4>
                    <p>You represent and warrant that (a) you have all rights, power and the full legal authority to enter into this Agreement (and if you are entering into this Agreement on behalf of any entity that you are fully authorized by such entity to so enter into this Agreement on its behalf), (b) you have carefully read this Agreement and shall comply with all of your obligations under this Agreement, the Privacy Policy and any other terms or conditions posted on the Website, (c) this Agreement is enforceable against you in accordance with its terms and conditions, (d) you shall not disparage Cabinfield, any of our personnel, the Website or any of our Products, and (e) regarding Your Content, (i) you hereby waive any and all claims (including, without limitation, claims based upon invasion of privacy, defamation, false light, or right of publicity) arising out of or related to any alteration, distortion or other use of your name, image or likeness or that of any third party which appears in any of Your Content (including without limitation your photograph or the photograph of a third party), (ii) the posting of Your Content by you does not and shall not violate any terms and conditions to which you are bound under this Agreement, any other applicable agreement, or any applicable law or regulation, (iii) you will not use any of Your Content provided other than as expressly permitted in this Agreement, and (iv) you are solely responsible for (and Cabinfield has no responsibility to you or to any third party) any of Your Content that you create, transmit, display, submit or post while using the Website and for the consequences of your actions, including without limitation any loss or damage which Cabinfield or any of its affiliated entities or any of their shareholders, officers, directors, members, managers, licensors, agents, employees, consultants, representatives and service providers (collectively, the “Cabinfield Parties”) may suffer which is related to any of Your Content including without limitation the enforcement of any rights in and to any of Your Content.	</p>

                    <h5 class="point">DISCLAIMER OF WARRANTIES</h5>
                    <p>YOUR USE OF THE WEBSITE AND ANY PRODUCTS YOU PURCHASE FROM US ARE ON AN “AS IS” AND “AS AVAILABLE” BASIS, WITH ALL FAULTS, AND AT YOUR SOLE RISK. OTHER THAN FOR ANY EXPRESS WRITTEN WARRANTY PROVIDED BY CABINFIELD ABOVE, NONE OF THE CABINFIELD PARTIES HAS OR SHALL HAVE ANY LIABILITY, OBLIGATION OR RESPONSIBILITY TO YOU OR ANY OTHER PERSON FOR ANY LOSS, DAMAGE, OR ADVERSE CONSEQUENCE ALLEGED TO HAVE HAPPENED OR WHICH HAS HAPPENED, DIRECTLY OR INDIRECTLY, THROUGH YOUR USE OF THE WEBSITE, RELIANCE ON ANY POSTED REVIEW,  OR OTHERWISE RELATED TO YOUR PURCHASE OR YOUR USE OF ANY PRODUCTS. CABINFIELD FURTHER DOES NOT MAKE ANY GUARANTY OF THE ACCURACY, CORRECTNESS, USEFULNESS OR COMPLETENESS OF, AND IS NOT LIABLE FOR ANY LOSSES OR DAMAGES ALLEGED TO ARISE FROM OR ARISING FROM OR RELATED TO, ANY USE OF THE WEBSITE OR ANY USE OF ANY PRODUCTS. SPECIFICALLY, AND TO THE EXTENT PERMITTED BY APPLICABLE LAW, CABINFIELD DISCLAIMS (A) ALL IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR ANY PARTICULAR PURPOSE REGARDING THE WEBSITE AND ANY PRODUCTS, AND (B) ALL WARRANTIES NOT EXPRESSLY MADE IN THIS AGREEMENT, INCLUDING WITHOUT LIMITATION IN CONNECTION WITH YOUR PURCHASE OF ANY PRODUCTS OR OTHERWISE YOUR USE OF THE WEBSITE. CABINFIELD DOES NOT WARRANT THAT THE WEBSITE WILL BE UNINTERRUPTED OR ERROR FREE OR FREE FROM VIRUSES OR OTHER HARMFUL COMPONENTS. WE DO NOT SELECT OR ENDORSE ANY INDIVIDUAL OR BUSINESS USER. WE DO NOT MAKE ANY WARRANTY, GUARANTEE, OR REPRESENTATION AS TO THE AUTHENTICITY, ABILITY, COMPETENCE, QUALITY, FINANCES, OR QUALIFICATIONS OF ANY USER OR THE STATEMENTS OR REVIEWS THEY MAY POST ON OUR WEBSITE. FURTHER, UNDER NO CIRCUMSTANCES SHALL CABINFIELD BE LIABLE IN ANY WAY FOR ANY LOSS OR DAMAGE ALLEGED TO ARISE OR ARISING OUT OF OR RELATED TO YOUR USE OF THE WEBSITE OR ANY PRODUCTS, RELIANCE ON ANY REVIEWS POSTED ON OUR WEBSITE, OR YOUR INTERACTION WITH ANY THIRD PARTY LINKED TO OR FROM THE WEBSITE OR OTHERWISE IN CONNECTION WITH YOUR PURCHASE OF ANY PRODUCTS.</p>

                    <h5 class="point">LIMITATION OF LIABILITY</h5>
                    <p>IN NO EVENT SHALL ANY OF THE CABINFIELD PARTIES BE LIABLE FOR LOST PROFITS OR FOR ANY SPECIAL, INCIDENTAL, INDIRECT, CONSEQUENTIAL OR PUNITIVE DAMAGES ARISING OUT OF OR RELATED TO, DIRECTLY OR INDIRECTLY, YOUR USE OF (A) THE WEBSITE (INCLUDING WITHOUT LIMITATION YOUR USE OF ANY CONTENT APPEARING ON THE WEBSITE OR YOUR LOSS OF DATA, INCOME, OR PROFIT, OR LOSS OR DAMAGE TO PROPERTY, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF, OR YOUR INABILITY TO USE, THE WEBSITE), OR (B) ANY PRODUCTS PURCHASED FROM US OR OTHERWISE AVAILABLE THROUGH THE WEBSITE, WHETHER OR NOT ANY OF THE CABINFIELD PARTIES HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE AGGREGATE LIABILITY OF THE CABINFIELD PARTIES COLLECTIVELY TO YOU OR ANY RELATED PERSON IN ALL CIRCUMSTANCES IS LIMITED TO THE LESSER OF (A) THE COST OF ALL PRODUCTS PURCHASED BY YOU FROM THE WEBSITE IN THE THREE (3) MONTH PERIOD IMMEDIATELY PRIOR TO THE ARISING OF SUCH LIABILITY, OR (B) FIVE HUNDRED DOLLARS ($500). SOME JURISDICTIONS DO NOT ALLOW FOR THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR SPECIAL, INCIDENTAL, INDIRECT, CONSEQUENTIAL OR PUNITIVE DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU, BUT IN SUCH A CASE SUCH LIABILITY WILL BE LIMITED TO THE GREATEST EXTENT PERMITTED BY LAW.</p>
                    
                    <h5 class="point">Indemnification</h5>
                    <p>You shall indemnify, defend and hold harmless Cabinfield and each of the other Cabinfield Parties from all claims, demands, causes of action and/or lawsuits (each, a "Claim" and collectively, "Claims") and all resulting costs, liabilities, losses, expenses, and damages, actual and consequential, direct and indirect, of every kind and nature, including without limitation reasonable attorneys' fees and disbursements (collectively, "Losses") made by any third party arising out of or related to (a) the breach by you of any of your representations, warranties, covenants under this Agreement or your failure to fulfill any of your obligations under this Agreement, (b) your negligence or misconduct, or (c) your violation of any law or regulation. You shall provide all applicable Cabinfield Parties with prompt written notice of any Claim or potential Claim of which you become aware. Upon the assertion or commencement of any Claim against one or more of the Cabinfield Parties by any third party that may give rise to liability of any such Cabinfield Party hereunder, you shall assume the control of the defense of such Claim at your sole expense with counsel reasonably acceptable to each such applicable Cabinfield Party; provided, however, that each such Cabinfield Party may take part in and/or fully assume such defense, in its sole discretion and at its own expense, after you assume the control thereof. You shall not enter into any settlement of any Claim which any of the Cabinfield Parties believes is adverse to its interests, without receiving the prior written consent of each of the Cabinfield Parties affected by such Claim. In no event shall any of the Cabinfield Parties be obligated to participate in any settlement which any such party reasonably believes would have an adverse effect on such party’s business interests.</p>
                    <h5 class="point">Privacy</h5>
                    <p>Cabinfield views the protection of your privacy as an important responsibility. The terms regulating the handling, use and storage of your PII and other information by us in connection with the Website is described in our <a href="/page/privacy-security.html">Privacy Policy</a> . By using the Website, you consent to the collection and use of your PII by us as described in the Privacy Policy. However, the handling, use and storage of your PII by any third party is subject to the privacy policy (if available) of such third party and not our Privacy Policy; for instance, when you provide your credit card information to our ecommerce gateway or other service providers, your PII will be subject to the privacy policy of our ecommerce gateway or other service providers.</p>
                    <h5 class="point">No Endorsement</h5>
                    <p>Cabinfield is neither affiliated with, nor sponsored or endorsed by, any specific product, service, methodology or person. The owners of any third party product, service, information, Trademark, copyright, or Content (other than Cabinfield’s own Trademark, copyrighted materials, and Content) appearing on the Website are not sponsors of Cabinfield or the Website and have not endorsed and are not affiliated with Cabinfield or the Website, and Cabinfield is not a sponsor and does not endorse any such third parties.</p>
                    <h5 class="point">No Agency</h5>
                    <p>No agency, partnership, joint venture, employee-employer or franchiser-franchisee relationship is intended or created between you and Cabinfield by this Agreement or as a result of your use of the Website or your purchase of any Products.</p>
                    <h5 class="point">Notices</h5>
                    <p>All notices hereunder shall be given by certified mail, postage prepaid and return receipt requested, to: Cabinfield LLC, Attn: Legal Department, 15 Cabinfield Circle, Lakewood, NJ 08701 and by email to e-mail at <a href="mailto:service@cabinfield.com">service@cabinfield.com</a>, and to a Registrant at the address and email listed which is provided to us by such Registrant. Notice shall be deemed given upon signature and upon receipt of such email.</p>
                </article>
                <article class="point-section only-point">
                    <h4 class="heading">GOVERNING LAW; ARBITRATION; NO CLASS CLAIMS; TIMELY FILING OF CLAIMS. </h4>
                    <p>This Agreement shall be governed by and construed in accordance with the laws of the State of New Jersey, excluding New Jersey’s choice-of-law principles. Any dispute arising out of or relating to this Agreement, including without limitation regarding any breach hereunder (other than for claims qualifying for small claims court, as described below), shall be finally resolved by binding arbitration administered by the American Arbitration Association under its Commercial Arbitration Rules, and judgment upon the award rendered by the arbitrator may be entered in any court having jurisdiction. The arbitration will be conducted in Lakewood, New Jersey, by an arbitrator with applicable industry expertise in ecommerce businesses, who shall be named in accordance with such rules. The award of the arbitrator shall be final and binding on you and us, without a right of appeal, and shall be accompanied by a statement of the reasons upon which the award is based, and such statement as well as all information concerning such arbitration proceedings including without limitation all evidence and materials submitted by you and/or us shall be deemed to be confidential information and shall not be made public by either you or us. If either party sues the other party and loses the claim which was the subject of such a suit, then the non-prevailing party shall pay the prevailing party’s costs and expenses, including but not limited to the prevailing party’s reasonable attorneys’ fees. NO ARBITRATION OR CLAIM UNDER THIS AGREEMENT SHALL BE JOINED TO ANY OTHER ARBITRATION OR CLAIM, AND NO CLASS ARBITRATION PROCEEDINGS SHALL BE PERMITTED. Notwithstanding the foregoing, claims or other disputes which are under the total value of Five Thousand Dollars ($5,000), shall be finally resolved in the Special Civil Part of the Civil Division (otherwise known as small claims court) in Ocean Superior Court located in Ocean County, NJ. Moreover, and notwithstanding the arbitration requirement above, we may apply to any court of competent jurisdiction for injunctive relief or enforcement of the above arbitration provision, without breach of such arbitration provision. YOU AGREE THAT REGARDLESS OF ANY STATUTE OR LAW TO THE CONTRARY, ANY CLAIM THAT YOU MAY HAVE AGAINST ANY OF THE CABINFIELD PARTIES WHICH ARISES OUT OF OR IS RELATED TO THIS AGREEMENT OR OTHERWISE YOUR USE OF THE WEBSITE OR PURCHASE OF ANY PRODUCTS MUST BE FILED BY YOU PURSUANT TO THIS SECTION WITHIN ONE (1) YEAR AFTER SUCH CLAIM OR CAUSE OF ACTION AROSE OR IS CLAIMED TO HAVE ARISEN.</p>
                </article>
                <article class="point-section only-point">
                    <h4 class="heading">Assignment</h4>
                    <p>You shall not resell or assign any of your rights, duties or obligations under this Agreement and any attempted assignment or delegation will be void and of no force or effect whatsoever. This Agreement may be automatically assigned by Cabinfield, in our sole discretion, to a third party, and such an assignment will inure to the benefit of our successors, assigns and/or licensees. Without limitation of the foregoing, we may sell, transfer or otherwise share some or all of our assets, including without limitation your PII, with any parent company, subsidiary, joint venture, and a company under our common control, as well as with a potential acquirer, including without limitation in connection with a merger, reorganization, or sale of assets, or in the event of bankruptcy. In each such an event, the PII we have collected from you may be one of the assets transferred.</p>
                </article>
                <article class="point-section only-point">
                    <h4 class="heading">No Waiver</h4>
                    <p>Our failure to act with respect to a breach by you or others does not waive our right to act with respect to a subsequent or similar breach or breaches. If Cabinfield does not exercise or enforce any legal right or remedy which is contained in this Agreement (or which Cabinfield has the benefit of under any applicable law or regulation), such action or inaction shall not be taken to be a formal waiver of Cabinfield’s rights, and all such rights or remedies shall still be available to Cabinfield.</p>
                </article>
                <article class="point-section only-point">
                    <h4 class="heading">General</h4>
                    <p>If any provision of this Agreement is held to be invalid by a court having competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of this Agreement, which shall remain in full force and effect. Section headings are for reference purposes only and in no way define, limit, construe or describe the scope or extent of such section. This Agreement and any ancillary terms and conditions referenced on the Website or otherwise provided by us sets forth the entire understanding and agreement between us with respect to your use of the Website and purchase of Products. The provisions of this Agreement shall survive termination or expiration to the extent necessary to carry out the obligations of you and Cabinfield under this Agreement.</p>
                </article>
                <article class="point-section only-point">
                    <h4 class="heading">Contact Us</h4>
                    <p>If you have any questions or concerns regarding the Website, please contact us by e-mail at <a href="mailto:service@cabinfield.com">service@cabinfield.com</a> or write to us at Cabinfield LLC, 15 Cabinfield Circle, Lakewood, NJ 08701.</p>
                </article>


            </section>
            <!-- .main-content  -->
        </div>
    </div>
</div>
<!-- .page-content ends  -->

<!-- include footer  -->
<?php include_once('sections/layouts/footer.php') ?>